-- PRISTUPOVA PRAVA
GRANT ALL ON CENA TO xblanc01;
GRANT ALL ON KLIENT TO xblanc01;
GRANT ALL ON POBYT TO xblanc01;
GRANT ALL ON POBYT_POKOJ TO xblanc01;
GRANT ALL ON POKOJ TO xblanc01;
GRANT ALL ON RECEPCNI TO xblanc01;
GRANT ALL ON REZERVACE TO xblanc01;
GRANT ALL ON SLUZBA TO xblanc01;
GRANT ALL ON TYP_POKOJE TO xblanc01;
GRANT ALL ON VYUZITI_SLUZBY TO xblanc01;