CREATE OR REPLACE PROCEDURE ODSTRANIT_KLIENTA (OS_CISLO NUMBER)
IS
BEGIN
  DELETE FROM VYUZITI_SLUZBY WHERE (VYUZITI_SLUZBY.POBYT_POKOJ IN (
    SELECT ID_POBYT_POKOJ FROM POBYT_POKOJ WHERE POBYT IN (
      SELECT ID_POBYT FROM POBYT WHERE (POBYT.VLASTNIK = ODSTRANIT_KLIENTA.OS_CISLO)))
  );
  DELETE FROM POBYT_POKOJ WHERE (POBYT_POKOJ.POBYT IN (
    SELECT ID_POBYT FROM POBYT WHERE (POBYT.VLASTNIK = ODSTRANIT_KLIENTA.OS_CISLO))
  );
	
	DELETE FROM POBYT WHERE (POBYT.VLASTNIK = ODSTRANIT_KLIENTA.OS_CISLO);
	DELETE FROM REZERVACE WHERE (REZERVACE.VLASTNIK = ODSTRANIT_KLIENTA.OS_CISLO);
  DELETE FROM KLIENT WHERE (KLIENT.OS_CISLO = ODSTRANIT_KLIENTA.OS_CISLO);
  COMMIT;
END ODSTRANIT_KLIENTA;
